### ISSUE TITLE
Left hand mode bug

### ISSUE THREAD

**Issue by Nitai610** [rcelyte/MappingExtensions#2] opened 2022-08-28 21:36 UTC
left hand moves blocks away from you in https://beatsaver.com/maps/922f (DADADADA)

**Comment by rcelyte** [comment] 2022-08-29 07:53
Upon investigation, I found a mistake in my mirroring logic. Can you confirm whether or not the issue is fixed in v0.21.3?

**Comment by Nitai610** [comment] 2022-08-29 09:48
Workes now thankyou

**Closed as completed** 2022-08-29 10:29 UTC
